### ISSUE TITLE
Rails force_ssl breaks the health check when behind a load balancer

### ISSUE THREAD

**Issue by zoltrain** [ianheggie/health_check#25]
While this can be solved at the web server level like so. 

e.g. Nginx

http://scottwb.com/blog/2013/10/28/always-on-https-with-nginx-behind-an-elb/

It would be good to add an exception via the health config to turn off the force_ssl at the health check controller level if you're terminating SSL upstream

In AWS's case it takes instance out of circulation as it keeps getting a 301.

**Comment by ianheggie** [comment]
Either 
1.  change it at the proxy level as per http://scottwb.com/blog/2013/10/28/always-on-https-with-nginx-behind-an-elb/ , or
2.  remove config.force_ssl = true from config/environments/*.rb to setting it at a controller level (thus removing the rack middleware and allowing health_check to receive the request), eg:

Either add an application base controller to force ssl (and whatever else) 
```
    class SslController < ApplicationController
      force_ssl
    end
```

Then use that instead of ApplicationController for all your controllers

**Comment by opsline-chetan** [comment]
In case someone else comes across this issue, there's a built-in method (at least as of this writing in Rails 5.2) of doing this:

https://api.rubyonrails.org/v5.2.1/classes/ActionDispatch/SSL.html

```
config.force_ssl = true
config.ssl_options = { redirect: { exclude: -> request { request.path =~ /healthcheck/ } } }
```
