### ISSUE TITLE
Writability checks

### ISSUE THREAD

**Issue by brandondrew** [ianheggie/health_check#61]
`health_check` is super-awesome, but (as far as I could tell) it does not check that databases (postgres and redis, in my case) are writable, which is generally important.  I used custom tests for this, but it seems logical to add checks for writability to `health_check`, either as part of the normal database and redis checks, or as additional checks that can be run.

(If it does actually test this already, then it would be helpful to make that explicit in the README.)

**Comment by ianheggie** [comment]
I don't check that the databases are writeable as opposed to contactable because I haven't seen or heard that failure happening in practise. All the ones I have seen are caught by the connection and version read check.  Have you ever seen it happen in practise?

If you are happy to share the custom test, I would be happy to add to the wiki for others to benefit from.

Otherwise if you can point to some failure scenarios that result in the database being readable but not writeable I will consider adding it to health_check.

**Comment by ianheggie** [comment]
I have closed this because I had not heard back to the request for further info, and I have never experienced this failure scenario myself.
